# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb70355b3a66c09b59ef3bb5f26b7c966e189e4d2f26878e6ffc1724e9f87926dab898f354acafaeac4fe6773e028e7ded352d2fd9472433a7ef956b5dacd689

test:
  secret_key_base: 6e04dc172a945d5c1529eedb61ba350dae214e7519fa6b0ca4b207d6e23a57300ca0c05f70837c86b1439322d2ba2018d92dfeeba3673d0265cb2f5c07b12f72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
